### ISSUE TITLE
Configure cron job on Circle CI

### ISSUE THREAD

**Issue by enocom** [enocom/gopher-reading-list#97]
One of the things we lost when transferring to Circle CI was running a build every 24 hours.

@mvxt If you have the time to do this, I would be grateful. Otherwise, I'm happy to handle it. You've done all the hard work.

**Comment by mvxt** [comment]
@enocom Here's one of the snippets I've used to configure nightly builds.

In short you'll want to specify workflows. So I'd add the following snippets to your config.yml file:
```
workflows:
  version: 2
  build-pipeline:
    jobs:
      - build

  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
```
`workflows` is a top-level item with version specification followed by various other parameters. In the above snippet we've defined two workflows: the first is the normal workflow which is always triggered on push to repo.

The second one is the one that is triggered to run once a day via CRON. I also added an additional filter so that we only run nightly builds on the master branch, and no other branches. You can omit that if you'd like.

Hope this makes sense and helps.
